-- AlterTable
ALTER TABLE "salary_rules" ADD COLUMN     "classPercent" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "harmfulnessPercent" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "holidayCoefficient" DOUBLE PRECISION DEFAULT 2,
ADD COLUMN     "regionalCoefficient" DOUBLE PRECISION DEFAULT 1,
ADD COLUMN     "taxPercent" DOUBLE PRECISION DEFAULT 13,
ADD COLUMN     "tripBonusPerHour" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "unionPercent" DOUBLE PRECISION DEFAULT 1,
ADD COLUMN     "zonalPercent" DOUBLE PRECISION DEFAULT 0;
